### ISSUE TITLE
Leadership pictures not all the same size (1 hour)

### ISSUE THREAD

**Issue by nimmerman** [HKNBetaEpsilon/new-hkn-website#2]
It would be nice if all of the pictures on the leadership page were the same size and organized nicely

**Comment by DavidSnider** [comment]
this could be an aspect ratio issue. If the pictures are not the same aspect ratio, you're going to have problems automatically making them the same size. 

What might be the best move is to enforce a certain cropping of pictures on upload, similar to facebook profile picture thumbnails.

**Comment by nimmerman** [comment]
It sounds like you are volunteering?!

**Comment by DavidSnider** [comment]
Oh god what have I done. I have literally no time at the moment what with 381 + exam and writing a new p3 for 281. If no one else gets to this I can take a look at it in ~ a month

**Comment by nimmerman** [comment]
6360be80e8d9eb257fcd3b2749f8570a2b14c501

da709bdcc7290416e01d4d52079b5b4c3efef910
