### ISSUE TITLE
NO SECURITY IN MANY ROUTINGS

### ISSUE THREAD

**Issue by zhanghan177** [HKNBetaEpsilon/new-hkn-website#21]
That's horrible!
For example, even if I am a pure electee, I can still access to http://127.0.0.1:8000/electee_turn_ins/ and (potentially) modify my turn_ins.
This vuln might be common in many different routes as well.

What do you think?

**Comment by jackkosaian** [comment]
I agree

**Comment by anksh** [comment]
Yeah I was looking at the db_cafe thing too and there's no protection there either - meaning anyone can come along and remove the last scanned item. 

Looking at some Django docs, we could use the [login_required](https://docs.djangoproject.com/en/1.9/topics/auth/default/#django.contrib.auth.decorators.login_required) decorator to start with, and then maybe move on to modifying functions in the respective views.py files to only give write access to admin users/Officers

We're already authenticating partially in our templates with `request.user.is_superuser`, looks like we just need to expand the scope of that to the actual views too.

**Comment by nimmerman** [comment]
Made a pull request, check it out!
