### ISSUE TITLE
Is there a reason why there is a pass statement?

### ISSUE THREAD

**Issue by zhanghan177** [HKNBetaEpsilon/new-hkn-website#29]
https://github.com/HKNBetaEpsilon/new-hkn-website/blob/master/src/hknWebsiteProject/views.py#L55
Just curious when I was reviewing the code for PR #28 It's not related to the change you made in that PR but it's the first time I saw the codebase. Shall we remove it?

**Comment by zhanghan177** [comment]
@nimmerman wanna take a quick look? It's just one line.

**Comment by nimmerman** [comment]
Ya just looks like an old line, feel free to delete it

**Comment by zhanghan177** [comment]
Cool no need to keep track of this issue any more. I will include it in the next patch.
