### ISSUE TITLE
Change color of Projects Calendar

### ISSUE THREAD

**Issue by anksh** [HKNBetaEpsilon/new-hkn-website#35]
The color of the [HKN] Projects calendar is very similar to that of the [HKN] Office Hours calendar (both are shades of green). It would be ideal if the Projects calendar was a different color from the rest.

It looks like the place to change this is approximately at lines 68-70 in home.html.

**Comment by anksh** [comment]
@gdhodge @arefai Shouldn't take too long, and would appreciate if you could look into this!

**Comment by arefai** [comment]
@anksh Fixed! Projects calendar events should be purple now.
