### ISSUE TITLE
Login in failure message (3 - 4 hours)

### ISSUE THREAD

**Issue by nimmerman** [HKNBetaEpsilon/new-hkn-website#4]
If you log in with a valid umich address but don't have a profile, you are just redirected to the home page. We should display some kind of error message.

**Comment by zhanghan177** [comment]
I'd be happy to help, but I can't do anything tonight. If this issue is still open tomorrow night, I will work on this :smiley:

**Comment by nimmerman** [comment]
Awesome! I'll be around North campus during the day tomorrow, let me know if you want me to walk you through how it all currently works.

**Comment by zhanghan177** [comment]
I was following the set up instruction on the wiki page, and I ran into problem when I was trying to login with my uniqname. After adding my uniqname as a member, I tried to login with my umich account while running local server. I got an Error 400 from Googla OAuth, and it indicates that my localhost doesn't match with any registered redirect URI. If you need I can send you a screenshot of the error message.

**Comment by nimmerman** [comment]
Are you using port 8000?

**Comment by sarparis** [comment]
Similarly, if you click login and are in a different gmail account (but not your umich) it doesn't do anything. Easily fixed if you know the issue (just log into umich in a different tab and then click login on HKN) but kinda annoying/confusing that it doesn't give you an error saying to login with your umich address. This also could be a separate issue if you think. Do with this comment what you may.
