### ISSUE TITLE
Finish Electee Tracking (2 - 3 hours)

### ISSUE THREAD

**Issue by nimmerman** [HKNBetaEpsilon/new-hkn-website#6]
The biggest aspect that is missing is being able to convert electees into actives

**Comment by zhanghan177** [comment]
Can we just update their status from 'E' to 'A'? And remove their history (or archive them) in the electeeManagement table?

**Comment by nimmerman** [comment]
Yes those are the technical steps that have to be done, but we need to create an easy to use way to preform those actions on electees who have complete all of their requirments

**Comment by zhanghan177** [comment]
I see.
Do you want to implement that functionality in the '/admin' panel?

**Comment by nimmerman** [comment]
No the admin page should just be for system admins not officers. It should be on either the "All Electee Progress" page if it can be done well (maybe with another column) or be put on its own page.

**Comment by zhanghan177** [comment]
okay, so I will set up myself as an officer and play around the dashboard, will that work?

**Comment by nimmerman** [comment]
Right now all of the things that will be for officers is for superusers, so just make yourself a superuser.

**Comment by zhanghan177** [comment]
Will work on this
